sudo: required
dist: trusty
language: php

# versi PHP
php:
  -7.1

# branch yang digunakan
branches:
  only:
    -master
    -develop

before_install:
  -curl -LO https://storage.googleapis.com/kubernetes-release/realese/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.text)/bin/linux/amd64/kubectl
  -chmod +x ./kubectl
  -sudo mv .kubectl/usr/local/bin/kubectl

before_script:

script: